# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Neer
  pod 'Firebase'
  pod 'Firebase/Messaging'
  
  pod 'KeychainAccess'
  pod 'Just'
  pod 'SwiftyRSA'
  pod 'MessageKit', '~> 3.0.0-swift5'

  target 'NeerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
