name: Build

on: [push]

jobs:

  unit_test_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Run unit tests
      run: |
        cd neer-backend
        ./gradlew test
        
  integration_test_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Run integration tests
      run: |
        cd neer-backend
        ./gradlew integrationTest
  
  build_backend:
    runs-on: ubuntu-latest
    needs: [ unit_test_backend, integration_test_backend ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Build neer-backend
      run: |
        cd neer-backend
        ./gradlew jib \
          -Djib.to.image=neerapp/backend:${GITHUB_SHA} \
          -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
