name: Build

on: [push]

jobs:
  build_backend:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Build neer-backend
      run: |
        cd neer-backend && ./gradlew jib -Djib.to.image=neerapp/backend:${GITHUB_SHA} -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
