name: Build

on: [push]

jobs:
  build_backend:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/docker/cli@master
      with:
        args: build -t neerapp/backend -f ./neer-backend/Dockerfile ./neer-backend
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/docker/cli@master
      with:
        args: push neerapp/backend:${GITHUB_SHA}
