name: Build

on: [push]

jobs:
  build_backend:

    runs-on: ubuntu-latest
    
    steps:
    - run: cd neer-backend
    - uses: actions/docker/cli@master
      args: build -t neerapp/backend:${{ GITHUB_REF }} .
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/docker/cli@master
      args: push neerapp/backend:${{ GITHUB_REF }}
